// O.Poncet 08/03/22
// Small macro to compqre Asimov dataset generated by combine -t -1 to MC data
// The ratio of the two histogram is also plotted
// Files needed : ztt.root containing Asimov dataset and higgsCombine.root in output and ztt.root in input
//Note that Asimov dataset is genereted and saved with options -t -1 --saveToys  of combine 

#include <TROOT.h>
#include <TObject.h>
#include <TMath.h>
#include <TString.h>
#include <TFile.h>
#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "TCanvas.h"
#include "RooPlot.h"
#include "TAxis.h"
#include "CMSStyle.h"


using namespace RooFit;

int asimov_MC(Char_t *channel, Char_t *observable)
{
    int nbin;
    double xmin, xmax;
    if (TString(observable).EqualTo("m_vis") == 1)
    {
        //cout << "check" << endl;
        nbin = 8;
        xmin = 50;
        xmax = 106;
    }
    else if (TString(observable).EqualTo("m_2") == 1)
    {
        nbin = 13;
        xmin = 0.3;
        xmax = 1.6;
    }
    else
    {
        "Error message, m_vis and m_2 are the only observable available";
    }
    // ----------------------------------
    // ASIMOV DATASET
    TFile *fcombine = new TFile("./output_UL2018/higgsCombine.mt_" + TString(observable) + "-" + TString(channel) + "_mtlt65_DeepTau-UL2018-13TeV.MultiDimFit.mH90.root");
    // fcombine->ls();
    TDirectory *dir = fcombine->GetDirectory("toys");
    // dir->ls();
    RooDataSet *dataset = (RooDataSet *)dir->Get("toy_asimov");
    // dataset->Print();
    // dataset->Print("v"); // print information about observables names and number of entries
    // dataset->get(0)->Print("v"); //gets the 0th entry of the dataset (if it exists), which is a RooArgSet, and prints the values of all the vars in that set

    // CONVERTING DATASET IN HISTO
    RooRealVar CMS_th1x("CMS_th1x", "CMS_th1x", 0, nbin);
    TH1 *hdata = dataset->createHistogram("CMS_th1x", nbin);
    for (int i = 1; i < nbin+1; i++)
    {
        hdata->SetBinError(i, sqrt(hdata->GetBinContent(i)));
    }
    // ----------------------------------
    // INPUT
    TFile *f = new TFile("./input/ztt_mt_tes_" + TString(observable) + ".inputs-UL2018-13TeV_mtlt65.root"); // Access to the data
    // f->ls();
    TDirectory *dirchannel = gFile->GetDirectory(channel);
    // dir->ls();

    TH1D *histo[10];
    Char_t histoNames[10][8] = {"ZTT", "ZL", "ZJ", "W", "VV", "TTT", "TTL", "TTJ", "ST", "QCD"};

    TH1D *htot = new TH1D("htot", "htot", nbin, xmin, xmax);

    // histograms of signal and background
    for (int i = 0; i < 10; i++)
    {
        histo[i] = (TH1D *)dirchannel->Get(histoNames[i]);
        htot->Add(histo[i]);
    }

    // CONVERTING TO HISTO WITH DIFFERENT BIN
    TH1D *hbin = new TH1D("hbin", "hbin", nbin, 0, nbin);
    for (int i = 1; i < nbin + 1; i++)
    {
        hbin->SetBinContent(i, htot->GetBinContent(i));
        //cout << "Bin " << i << " = " << htot->GetBinContent(i) << endl;
        //cout << "Error= " << hdata->GetBinError(i) << endl;
    }

    // ----------------------------------
    // PLOT
    SetCmsStyle();
    //gStyle->SetOptStat(000000); 
    TCanvas *c = new TCanvas();
    TPad *pad1 = new TPad("pad1", "", 0, 0.42, 1, 1);
    pad1->SetTopMargin(0.05);
    pad1->SetBottomMargin(0.03);
    pad1->SetRightMargin(0.05);
    TPad *pad2 = new TPad("pad2", "", 0, 0, 1, 0.4);
    pad2->SetTopMargin(0.02);
    pad2->SetBottomMargin(0.28);
    pad2->SetRightMargin(0.05);
    pad1->Draw();
    pad2->Draw();

    // PLOT RATIO
    pad1->cd();
    //gStyle->SetLegendTextSize(0.02); // Legend
    hbin->SetTitle("");
    hbin->GetYaxis()->SetTitle("event");
    hbin->SetMarkerStyle(5);
    hbin->Draw("hist p");
    hdata->SetMarkerStyle(2);
    hdata->Draw("same");
    auto leg1 = new TLegend(0.75,0.7,0.9,0.85);
    leg1->AddEntry(hbin, "MC data", "p");
    leg1->AddEntry(hdata, "Asimov dataset", "p");
    leg1->Draw();
    c->Update();

    // PLOT RATIO
    pad2->cd();
    TH1D *hratio = (TH1D *)hbin->Clone();
    hratio->Divide(hdata);
    hratio->SetMarkerStyle(20);
    hratio->SetTitle("");
    hratio->GetXaxis()->SetTitle("nbins");
    hratio->GetYaxis()->SetTitle("MC/Asimov");
    hratio->GetYaxis()->SetRangeUser(0.9 ,1.1);
    hratio->Draw();
    CMSLabel(0,0.001, TString(observable) + "-" + TString(channel), kBlack, 0.10);


    c->Update();
    c->SaveAs("./Asimov/Asimov_MC_" + TString(observable) + "-" + TString(channel) + "-UL2018-13TeV_mtlt65.root");

    return 0;

    // BACKUP
    /*
    // ZTT WORKSAPCE
    TFile *fztt = new TFile("./output_UL2018/ztt_mt_"+TString(observable)+"-"+TString(channel)+"_mtlt65_DeepTau-UL2018-13TeV.root"); // workspace
    //  Retrieve workspace from file
    RooWorkspace *w = (RooWorkspace *)fztt->Get("w");
    // Import model and all its components into the workspace
    // Retrieve x,model and data from workspace
    RooRealVar *x = w->var("CMS_th1x");
    // RooAbsPdf *model = w->pdf("pdf_binDM10");
    // RooAbsData *data = w->data("data_obs");
    // Print structure of composite pdf
    // x->Print("t");
    // model->Print("t");

     // // // Plot data and PDF overlaid
    // RooPlot *xframe = x->frame(Title("Model and data read from workspace"));
    // RooPlot *mframe = CMS_th1x.frame(Title("Model and data read from workspace"));
    // dataset->plotOn(xframe);
    // dh.plotOn(mframe);
    // model->plotOn(xframe);
    // xframe->Draw();
    // mframe->Draw("same");
    */
}

int asimov()
{
    Char_t channel[5][10] = {"baseline", "DM0", "DM1", "DM10", "DM11"};
    Char_t observable[2][10] = {"m_vis", "m_2"};

    asimov_MC(channel[2], observable[1]);

    return 0;
}