#
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional


# Typically, each channel will have its own config file; combination can be done at datacard level

channel: mutau

# Tag can be used to differentiate between scenarios

tag: "_mutau_mt40cut_DM_Dt2p5_JetM_muVT_puppimet" # Used to dervied TauES SFs for 2022_preEE

baselineCuts: "q_1*q_2<0 && iso_1<0.15 && idDecayModeNewDMs_2 && idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && rawDeepTau2018v2p5VSmu_2>=0.97 && !lepton_vetoes_notau && metfilter "
# idDeepTau2018v2p5VSjet_2>=5 = Medium WP
# idDeepTau2018v2p5VSe_2>=2 = VVLoose WP
# idDeepTau2018v2p5VSmu_2>=4 = Tight WP

# These regions will be defined when creating inputs or making plots
# At this point, they do not need to be exclusive; 
# PLEASE NOTE:
#     - which regions are included in the fit will be defined in obervables section --> adjust when changing regions
#     - additional cross section scale factors applied to some processes need to be given in these regions to be considered --> adjust in scaleFactors section

regions:
    baseline:
        definition: "mt_1<40"
        title: "baseline"
    DM0: 
        definition: "dm_2==0 && mt_1<40"
        title: "h^{#pm}"
    DM1: 
        definition: "dm_2==1 && mt_1<40"
        title: "h^{#pm}#pi^{0}"
    DM10: 
        definition: "dm_2==10 && mt_1<40"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        definition: " dm_2==11 && mt_1<40"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

plottingOrder: ["DM11", "DM10","DM1", "DM0"]

tesRegions:
    DM0: 
        title: "h^{#pm}"
    DM1: 
        title: "h^{#pm}#pi^{0}"
    DM10: 
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###

tid_SFRegions:
    DM0: 
        title: "h^{#pm}"
    DM1: 
        title: "h^{#pm}#pi^{0}"
    DM10: 
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###

# Observables to be fitted and plotted
# binning: as defined in TH1 (nbins, xmin, xmax)
# regions: (defined separately) to be included in the fit for this observable

observables:
    m_vis:
        binning: [36,20, 200] #binning=10
        title: "m_{vis}"
        extra:
            #cut: "50<m_vis && m_vis<150"
            cut: "20<m_vis && m_vis<200"
        fitRegions: [DM0, DM1, DM10, DM11]
        scanRegions: ["DM0", "DM1", "DM10", "DM11"] 
        # fitRegions: ["DM0"]
        # scanRegions: ["DM0"]

# Assume that this code is meant to fit TES variations; more options could be added when adding other POIs

TESvariations: 
    values: [0.900, 0.902, 0.904, 0.906, 0.908, 0.910, 0.912, 0.914, 0.916, 0.918, 0.920, 0.922, 0.924, 0.926, 0.928, 0.930, 0.932, 0.934, 0.936, 0.938, 0.940, 0.942, 0.944, 0.946, 0.948, 0.950, 0.952, 0.954, 0.956, 0.958, 0.960, 0.962, 0.964, 0.966, 0.968, 0.970, 0.972, 0.974, 0.976, 0.978, 0.980, 0.982, 0.986, 0.988, 0.990, 0.992, 0.994, 0.996, 0.998, 1.000, 1.002, 1.004, 1.006, 1.008, 1.010, 1.012, 1.014, 1.016, 1.018, 1.020, 1.022,1.024, 1.026, 1.028, 1.030] #1.024 0.984

    processes: ["ZTT"]

# Should add bin-by-bin variations (stat. uncertainties) for signal and backgrounds?

fitSpecs:
    doBBB: doShapes
    signalBBB: True
    backgroundBBB: True


# Samples to be used and association to processes entering analysis
# Possibility to remove or add specific weights / SFs from global weight

samples:
    filename: "$PICODIR/$SAMPLE_$CHANNEL$TAG.root"
    join: ["VV","TT","ST"]
    split:
        DY: [ ["ZTT","genmatch_2==5"], ["ZL","genmatch_2>0 && genmatch_2<5"], ["ZJ","genmatch_2==0"] ]
        TT: [["TTT","genmatch_2==5"], ["TTL","genmatch_2>0 && genmatch_2<5"], ["TTJ","genmatch_2==0"] ]
        #ST: [("STT","genmatch_2==5"),("STJ","genmatch_2<5")]
    rename:
        WJ: "W"
    data: "data_obs"
    removeSFs: ["idweight_2"]
    #addSFs: []


# # Processes taken into account in analysis

processes: ["ZTT","ZL","ZJ","W","VV","ST","TTT","TTL","TTJ","QCD","data_obs"]

# # Systematic uncertainties: can have effect shape or lnN (normalisation)

systematics:
    LTF:
        effect: "shape"
        processes: ["ZL", "TTL"]
        name: "shape_mTauFake_$BIN"
        title: "+/- 2% LTF shape"
        variations: ["Up", "Down"]
        sampleAppend: ["_LTFUp","_LTFDown"]
    JTF:
        effect: "shape"
        processes: ["ZJ", "TTJ", "W"]
        name: "shape_jTauFake_$BIN"
        title: "+/- 10% JTF"
        variations: ["Up", "Down"]
        sampleAppend: ["_JTFUp","_JTFDown"]
    # shape_mTauFake:
    #     effect: "shape"
    #     processes: ["ZL", "TTL"]
    #     name: "shape_mTauFakeSF"
    #     title: "LTF rate syst"
    #     variations: ["Up", "Down"]
    #     nomWeight: "ltfweight_2"
    #     altWeights: ["ltfweightUp_2", "ltfweightDown_2"]
    shape_dy:
        effect: "shape"
        processes: ["ZTT", "ZL", "ZJ"]
        name: "shape_dy"
        title: "+/- 10% Zptweight"
        variations: ["Up", "Down"]
        nomWeight: "zptweight"
        altWeights: ["(zptweight+0.1*(zptweight-1))", "(zptweight-0.1*(zptweight-1))"]
    muonFakerate_$BIN:
        effect: "lnN"
        processes: ["ZL", "TTL"]
        scaleFactor: 1.50
    lumi:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.025
    eff_m:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.02
    # xsec_dy:
    #     effect: "lnN"
    #     processes: ["ZTT", "ZL", "ZJ"]
    #     scaleFactor: 1.02
    xsec_tt:
        effect: "lnN"
        processes: ["TTT", "TTL", "TTJ"]
        scaleFactor: 1.06
    xsec_st:
        effect: "lnN"
        processes: ["ST"]
        scaleFactor: 1.05
    xsec_vv:
        effect: "lnN"
        processes: ["VV"]
        scaleFactor: 1.05
    # norm_wj:
    #     effect: "lnN"
    #     processes: ["W"]
    #     scaleFactor: 1.08
    norm_qcd:
        effect: "lnN"
        processes: ["QCD"]
        scaleFactor: 1.10
    rate_jTauFake_$BIN:
        effect: "lnN"
        processes: ["W","QCD","ZJ","TTJ","STJ"]
        scaleFactor: 1.15

# Additional scale factors per year for specific processes (correction of xsec, reco SFs, etc.) for post fit plot
scaleFactors:
  tid_SF:
    processes: ['ZTT']
    values:
      {
      'DM11': 0.876569092274,
      'DM10': 1.0,
      'DM1': 1.0,
      'DM0': 0.890349209309,
      }
  xsec_dy:
    processes: ['ZTT', 'ZL', 'ZJ']
    values:
      {
      'DM11': 0.989084005356,
      'DM10': 0.992536365986,
      'DM1': 0.995644211769,
      'DM0': 0.990213751793,
      }
  sf_W:
    processes: ['W']
    values:
      {
      'DM11': 1.96275997162,
      'DM10': 1.52390229702,
      'DM1': 0.515506386757,
      'DM0': 0.873363137245,
      }
  muonFakerate_$BIN:
    processes: ['ZL', 'TTL']
    values:
      {
      'DM11': 0.997734295902775,
      'DM10': 1.001727624214255,
      'DM1': 1.4079233407975,
      'DM0': 1.3683696985245,
      }
  lumi:
    processes: ['ZTT', 'ZL', 'ZJ', 'TTT', 'TTL', 'TTJ', 'W', 'ST', 'VV']
    values:
      {
      'DM11': 0.9986512935720375,
      'DM10': 0.996533153951175,
      'DM1': 0.99489619508385,
      'DM0': 0.9979685820639125,
      }
  eff_m:
    processes: ['ZTT', 'ZL', 'ZJ', 'TTT', 'TTL', 'TTJ', 'W', 'ST', 'VV']
    values:
      {
      'DM11': 0.999172832518816,
      'DM10': 0.99777681425214,
      'DM1': 0.99632256686688,
      'DM0': 0.998702682852746,
      }
  xsec_tt:
    processes: ['TTT', 'TTL', 'TTJ']
    values:
      {
      'DM11': 0.996803872585294,
      'DM10': 0.98549684792758,
      'DM1': 0.9743112736940199,
      'DM0': 0.999119414407762,
      }
  xsec_st:
    processes: ['ST']
    values:
      {
      'DM11': 0.999316757638005,
      'DM10': 0.998640028573575,
      'DM1': 0.99783716816455,
      'DM0': 0.9996179952751845,
      }
  xsec_vv:
    processes: ['VV']
    values:
      {
      'DM11': 0.999276140751315,
      'DM10': 0.997930890507995,
      'DM1': 0.99866256257519,
      'DM0': 0.999802185711451,
      }
  norm_qcd:
    processes: ['QCD']
    values:
      {
      'DM11': 0.9747991383076,
      'DM10': 0.9671005368233,
      'DM1': 1.154038190842,
      'DM0': 0.9690465241671,
      }
  rate_jTauFake_$BIN:
    processes: ['W', 'QCD', 'ZJ', 'TTJ', 'STJ']
    values:
      {
      'DM11': 0.92324378788465,
      'DM10': 0.89218066036705,
      'DM1': 1.3161105275154998,
      'DM0': 0.9142732650041501,
      }
