#
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional


# Typically, each channel will have its own config file; combination can be done at datacard level
channel: utau

# Tag can be used to differentiate between scenarios

tag: "_mutau_mt65_DM_Dt2p5_VSJetMedium_puppimet"

baselineCuts: "q_1*q_2<0 && iso_1<0.15 && idDecayModeNewDMs_2 && idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSe_2>=2 && ^&& !lepton_vetoes_notau && metfilter "
# idDeepTau2018v2p5VSjet_2>=5 = Medium WP
# idDeepTau2018v2p5VSe_2>=2 = VVLoose WP
# idDeepTau2018v2p5VSmu_2>=4 = Tight WP

# These regions will be defined when creating inputs or making plots
# At this point, they do not need to be exclusive; 
# PLEASE NOTE:
#     - which regions are included in the fit will be defined in obervables section --> adjust when changing regions
#     - additional cross section scale factors applied to some processes need to be given in these regions to be considered --> adjust in scaleFactors section

regions:
    baseline:
        definition: "q_1*q_2<0"
        title: "baseline"
    DM0: 
        definition: "dm_2==0"
        title: "h^{#pm}"
    DM1: 
        definition: "dm_2==1"
        title: "h^{#pm}#pi^{0}"
    DM10: 
        definition: "dm_2==10"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        definition: " dm_2==11"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}"

plottingOrder: ["DM11", "DM10","DM1", "DM0"]

tesRegions:
    DM0: 
        title: "h^{#pm}"
    DM1: 
        title: "h^{#pm}#pi^{0}"
    DM10: 
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###

tid_SFRegions:
    DM0: 
        title: "h^{#pm}"
    DM1: 
        title: "h^{#pm}#pi^{0}"
    DM10: 
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###

# Observables to be fitted and plotted
# binning: as defined in TH1 (nbins, xmin, xmax)
# regions: (defined separately) to be included in the fit for this observable

observables:
    m_vis:
        binning: [10,50, 150] #binning=10
        title: "m_{vis}"
        extra:
            cut: "50<m_vis && m_vis<150"
        fitRegions: [DM0, DM1, DM10, DM11]
        scanRegions: ["DM0", "DM1", "DM10", "DM11"] 


# Assume that this code is meant to fit TES variations; more options could be added when adding other POIs

TESvariations: 
    values: [0.970, 0.972, 0.974, 0.976, 0.978, 0.980, 0.982, 0.986, 0.988, 0.990, 0.992, 0.994, 0.996, 0.998, 1.000, 1.002, 1.004, 1.006, 1.008, 1.010, 1.012, 1.014, 1.016, 1.018, 1.020, 1.022,1.024, 1.026, 1.028, 1.030] #1.024 0.984

    processes: ["ZTT"]

# Should add bin-by-bin variations (stat. uncertainties) for signal and backgrounds?

fitSpecs:
    doBBB: doShapes
    signalBBB: True
    backgroundBBB: True


# Samples to be used and association to processes entering analysis
# Possibility to remove or add specific weights / SFs from global weight

samples:
    filename: "$PICODIR/$SAMPLE_$CHANNEL$TAG.root"
    join: ["VV","TT","ST"]
    split:
        DY: [ ["ZTT","genmatch_2==5"], ["ZL","genmatch_2>0 && genmatch_2<5"], ["ZJ","genmatch_2==0"] ]
        TT: [["TTT","genmatch_2==5"], ["TTL","genmatch_2>0 && genmatch_2<5"], ["TTJ","genmatch_2==0"] ]
    rename:
        WJ: "W"
    data: "data_obs"
    removeSFs: ["idweight_2"]
    #addSFs: []


# # Processes taken into account in analysis

processes: ["ZTT","ZL","ZJ","W","VV","ST","TTT","TTL","TTJ","QCD","data_obs"]

# # Systematic uncertainties: can have effect shape or lnN (normalisation)

systematics:
    LTF: # lepton fake rate energy scale 
        effect: "shape"
        processes: ["ZL", "TTL"]
        name: "shape_mTauFake_$BIN"
        title: "+/- 3% LTF shape"
        variations: ["Up", "Down"]
        sampleAppend: ["_LTFUp","_LTFDown"]
    JTF:
        effect: "shape"
        processes: ["ZJ", "TTJ", "W"]
        name: "shape_jTauFake_$BIN"
        title: "+/- 10% JTF"
        variations: ["Up", "Down"]
        sampleAppend: ["_JTFUp","_JTFDown"]
    # shape_mTauFake: # Not defined for 2022
    #     effect: "shape"
    #     processes: ["ZL", "TTL"]
    #     name: "shape_mTauFakeSF"
    #     title: "LTF rate syst"
    #     variations: ["Up", "Down"]
    #     nomWeight: "ltfweight_2"
    #     altWeights: ["ltfweightUp_2", "ltfweightDown_2"]
    shape_dy:
        effect: "shape"
        processes: ["ZTT", "ZL", "ZJ"]
        name: "shape_dy"
        title: "+/- 10% Zptweight"
        variations: ["Up", "Down"]
        nomWeight: "zptweight"
        altWeights: ["(zptweight+0.1*(zptweight-1))", "(zptweight-0.1*(zptweight-1))"]
    muonFakerate:
        effect: "lnN"
        processes: ["ZL", "TTL"]
        scaleFactor: 1.50
    lumi:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.025
    eff_m:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.02
    # xsec_dy:
    #     effect: "lnN"
    #     processes: ["ZTT", "ZL", "ZJ"]
    #     scaleFactor: 1.02
    xsec_tt:
        effect: "lnN"
        processes: ["TTT", "TTL", "TTJ"]
        scaleFactor: 1.06
    xsec_st:
        effect: "lnN"
        processes: ["ST"]
        scaleFactor: 1.05
    xsec_vv:
        effect: "lnN"
        processes: ["VV"]
        scaleFactor: 1.05
    # norm_wj:
    #     effect: "lnN"
    #     processes: ["W"]
    #     scaleFactor: 1.08
    norm_qcd:
        effect: "lnN"
        processes: ["QCD"]
        scaleFactor: 1.10
    rate_jTauFake_$BIN:
        effect: "lnN"
        processes: ["W","QCD","ZJ","TTJ","STJ"]
        scaleFactor: 1.15

